title: Burning Technologies
author: Mrsha2nk 
email: shashank@randomdomain.com
description: > # this means to ignore newlines until "baseurl:"
  this blog sucks please move to better one!, this blog is just a test from 
  github learning course do-not-take-it-seriously!!!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

#theme
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
